config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'profiles/sponsorship'
  devise_for :users
  root to: 'pages#home'
  get 'my_profile', to: 'profiles#show', as: :my_profile
  # get 'community', to: 'posts#index', as: :community
  resources :courses, only: [:index, :show] do
    resources :posts, only: [:create]
  end
  resources :posts, only: [:index, :create, :destroy] do
    resources :upvotes, only: :create
    resources :emojis, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :participations, only: [] do
    collection do
      get :past_participations
      get :upcoming_participations
      get :favorites
    end
    member do
      patch :add_in_favorite
    end
  end
  resources :invitations, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :course

  scope :past, -> { joins(:course).where("courses.start_at < ?", Time.now) }
  scope :upcoming, -> { joins(:course).where("courses.start_at > ?", Time.now) }
  scope :favorites, -> { where("favorite > ?", true) }

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def past_participations
    @past_participations = Participation.past.where(user: current_user).order(:id).map { |p| p.course }
    authorize(:participation, :past_participations?)

    if params[:query] && !params[:query].empty?
      PgSearch::Multisearch.rebuild(Course)
      PgSearch::Multisearch.rebuild(Chef)
      @results = PgSearch.multisearch(params[:query])

      @courses = []
      if @results.group_by(&:searchable_type)["User"]
        @results.group_by(&:searchable_type)["User"].each do |chef|
          chef.searchable.courses.each do |course|
            if @past_participations.include?(course)
              @courses << course
            end
          end
        end
      end

      if @results.group_by(&:searchable_type)["Course"]
        @results.group_by(&:searchable_type)["Course"].each do |course|
          if @past_participations.include?(course.searchable)
              @courses << course.searchable
          end
        end
      end
    else
      @courses = @past_participations
    end

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'participations/list_participations', locals: { courses: @courses }, formats: [:html] }
    end
  end

  def upcoming_participations
    @upcoming_participations = Participation.upcoming
    authorize(:participation, :upcoming_participations?)
  end

  def favorites
    @favorites = Participation.favorites
    authorize(:participation, :favorites?)
  end

  def create
    @course = Course.find(params[:course_id])
    @participation = Participation.new(participation_params)
    @participation.course = @course
    @participation.user = current_user
    authorize @participation
    if @participation.save
      redirect_to course_path(@course), notice: "Demande de réservation envoyée !"
    else
      render :new
    end
  end


  def add_in_favorite
    @participation = Participation.find(params[:id])
    @participation.favorite == false ? @participation.update(favorite: true) : @participation.update(favorite: false)
    authorize @participation

    respond_to do |format|
      format.html { redirect_to past_participations_participations_path }
      format.text { render partial: "card_course", locals: { course: @participation.course }, formats: [:html] }
    end
  end

  private

  def participation_params
    params.require(:participation).permit(:favorite)
  end
end

app/views/participations/_card_course.html.erb
<div class="card-course" data-controller="favorite" data-favorite-target="card">
  <%= link_to course_path(course) do %>
      <%= cl_image_tag course.photo.key %>
  <% end %>
    <div class="card-course-infos">
      <div class="mb-1">
        <h2><%= course.title %></h2>
      </div>
      <div>
        <p>Chef <%= course.chef.user.first_name %> <%= course.chef.user.last_name %></p>
        <p>Temps de réalisation : <%= course.duration %> minutes</p>
      </div>
    </div>
    <div class="fav-icon">
      <%= link_to add_in_favorite_participation_path(course.participations.find_by(user_id: current_user.id)), data: {favorite_target: "link", action: "click->favorite#toggleFav"} do %>
        <i class="<% if course.participations.find_by(user_id: current_user.id).favorite? %>fas<% else %>far<% end %> fa-heart"></i>
      <% end %>
    </div>
</div>

app/views/participations/_list_participations.html.erb
<div data-search-participations-target="list">
  <div class="cards">
    <% courses.each do |course| %>
      <%= render "card_course", course: course %>
    <% end %>
  </div>
</div>

app/views/participations/favorites.html.erb
<%= render "shared/dashboard_navigation" %>
<div class="container container-top">
  <div class="cards">
      <% current_user.participations.each do |participation| %>
        <%if participation.favorite == true %>
          <div class="card-course">
            <%= link_to course_path(participation.course) do %>
                <%= cl_image_tag participation.course.photo.key %>
            <% end %>
              <div class="card-course-infos">
                <div class="mb-1">
                  <h2><%= participation.course.title %></h2>
                </div>
                <div>
                  <p>Chef <%= participation.course.chef.user.first_name %> <%= participation.course.chef.user.last_name %></p>
                  <p>Temps de réalisation : <%= participation.course.duration %> minutes</p>
                </div>
              </div>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/participations/past_participations.html.erb
<%= render "shared/dashboard_navigation" %>
<div class="container container-top" data-controller="search-participations">
  <div>
    <div class="d-flex justify-content-between">
      <div style="width: 100%">
        <%= form_with url:past_participations_participations_path, method: :get, html: { class:
          'mb-4', data: { search_participations_target: 'form' } } do |f| %>
          <%= f.text_field :query,
            class: "form-control",
            placeholder: "Retrouver un ancien cours, un chef, etc",
            style: "height: 50px; ",
            value: params[:query],
            data: { search_participations_target: 'input',
            action: 'keyup->search-participations#update' } %>
      </div>
      <div style="padding-left: 4px">
        <%= submit_tag "Rechercher", class: "button" %>
      </div>
      <% end %>
    </div>
  </div>
  <br>
  <%= render 'list_participations', courses: @courses %>
</div>
<br>

app/views/participations/upcoming_participations.html.erb
<%= render "shared/dashboard_navigation" %>
<div class="container container-top">
  <div class="cards">
    <% current_user.participations.upcoming.each do |participation| %>
      <div class="card-course">
        <%= link_to course_path(participation.course) do %>
            <%= cl_image_tag participation.course.photo.key %>
        <% end %>
        <div class="card-course-infos">
          <div class="mb-1">
            <h2><%= participation.course.title %></h2>
          </div>
          <div>
            <p>Chef <%= participation.course.chef.user.first_name %> <%= participation.course.chef.user.last_name %></p>
            <p>Temps de réalisation : <%= participation.course.duration %> minutes</p>
          </div>
        </div>
    <% end %>
  </div>
</div>