config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'profiles/sponsorship'
  devise_for :users
  root to: 'pages#home'
  get 'my_profile', to: 'profiles#show', as: :my_profile
  # get 'community', to: 'posts#index', as: :community
  resources :courses, only: [:index, :show] do
    resources :posts, only: [:create]
  end
  resources :posts, only: [:index, :create, :destroy] do
    resources :upvotes, only: :create
    resources :emojis, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :participations, only: [] do
    collection do
      get :past_participations
      get :upcoming_participations
      get :favorites
    end
    member do
      patch :add_in_favorite
    end
  end
  resources :invitations, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_dashboard_navigation.html.erb
<div class="dashboard-navigation list-in-line">
  <div class="container">
    <ul class="list-inline">
      <li class="list-inline-item margin-list"><p><%= link_to "Mon profil", my_profile_path, class: "#{ "active" if controller_name == "profiles" && action_name == "show" }" %></p></li>
      <li class="list-inline-item margin-list"><p><%= link_to "Mes prochains cours", upcoming_participations_participations_path, class: "#{ "active" if controller_name == "participations" && action_name == "upcoming_participations" }" %></p></li>
      <li class="list-inline-item margin-list"><p><%= link_to "Mes cours favoris", favorites_participations_path, class: "#{ "active" if controller_name == "participations" && action_name == "favorites" }" %></p></li>
      <li class="list-inline-item"><p><%= link_to "Mes cours passés", past_participations_participations_path, class: "#{ "active" if controller_name == "participations" && action_name == "past_participations" }" %></p></li>
    </ul>
  </div>
</div>

app/views/shared/_emojis.html.erb
<div class="d-flex" data-controller="emojis">
  <div>
    <% post.emojis_counters.each do |emoji, counter| %>
      <span class="mr-1">
        <span><%= emoji %></span>
        <span><%= counter %></span>
      </span>
    <% end %>
  </div>
  <div>
    <%= simple_form_for [post, Emoji.new], html: {'data-emojis-target': "form"} do |f| %>
      <%= f.input :content, collection: Emoji::EMOJIS, label: false, input_html: {'data-action': "change->emojis#submit"}, prompt: "" %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-6">
        <h2>FoodClass</h2>
        <p>Abonnez-vous à la newsletter :</p>
        <p>la_newsletter@foodclass.com</p>
      </div>
      <div class="col-12 col-lg-6">
      <p>
        <a href="#!" class="text-reset">Centre d'aide</a>
      </p>
      <p>
        <a href="#!" class="text-reset">Nos cuisiniers</a>
      </p>
      <p>
        <a href="#!" class="text-reset">Informations de sécurité</a>
      </p>
      <p>
        <a href="#!" class="text-reset">Ressources</a>
      </p>
      </div>
  </div>
</div>

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    <div>
       © 2022 Copyright:
    <a class="text-reset fw-bold" href="https://kitt.lewagon.com/camps/800/flashcards">Tous droits réservés</a>
    </div>
    <div class="reseaux">
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
    </div>
  </div>
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top navbar-global navbar-foodclass" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar" data-navbar-home-value="<%= action_name == "home"%>">
  <div class="container">
    <%= link_to "Réserver un cours", courses_path, class:"navbar-brand" %>

    <% if user_signed_in? %>
      <%= link_to "FoodClass.", root_path, class:"title-navbar" %>
    <% else %>
      <%= link_to "FoodClass.", root_path, class:"title-navbar-deconnected" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item mx-5 navbar-link">
          <%= link_to "Communauté", posts_path, class: "nav-link navbar-foodclass link-community", 'data-action': "click->transition#show"%>
        </li>
          <li class="nav-item dropdown">
            <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", my_profile_path, class: "dropdown-item" %>
              <%= link_to "Mes prochains cours", upcoming_participations_participations_path, class: "dropdown-item" %>
              <%= link_to "Mes cours favoris", favorites_participations_path, class: "dropdown-item" %>
              <%= link_to "Mes cours passés", past_participations_participations_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item navbar-link">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link navbar-foodclass link-community" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>