config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'profiles/sponsorship'
  devise_for :users
  root to: 'pages#home'
  get 'my_profile', to: 'profiles#show', as: :my_profile
  # get 'community', to: 'posts#index', as: :community
  resources :courses, only: [:index, :show] do
    resources :posts, only: [:create]
  end
  resources :posts, only: [:index, :create, :destroy] do
    resources :upvotes, only: :create
    resources :emojis, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :participations, only: [] do
    collection do
      get :past_participations
      get :upcoming_participations
      get :favorites
    end
    member do
      patch :add_in_favorite
    end
  end
  resources :invitations, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :participation
  belongs_to :course
  has_many :comments, dependent: :destroy
  has_many :upvotes, dependent: :destroy
  has_many :emojis, dependent: :destroy
  has_one_attached :photo

  def emojis_counters
    emojis.group(:content).count
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = policy_scope(Post).order(posted_at: :desc)
    @post = Post.new
    if current_user
      @courses = current_user.courses_as_participant.where("end_at < ?", Time.now)
    end
  end

  def new
    @post = Post.new
  end

  def create
    if params[:course_id].present?
      @course = Course.find(params[:course_id])
      @post = Post.new(post_params)
      @participation = current_user.participations.find_by(course: @course)
      @post.course = @course
      @post.participation = @participation
      authorize @post
      if @post.save
        redirect_to course_path(@course)
      else
        render 'courses/show'
      end
    else
      @course = Course.find(params[:post][:course_id])
      @post = Post.new(post_params)
      @participation = current_user.participations.find_by(course: @course)
      @post.course = @course
      @post.participation = @participation
      authorize @post
      if @post.save
        redirect_to posts_path
      else
        @posts = policy_scope(Post).order(posted_at: :desc)
        @courses = current_user.courses_as_participant.where("end_at < ?", Time.now)
        render 'posts/index'
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post
    @post.destroy

    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:content, :photo)
  end
end

app/views/posts/index.html.erb
<div class="container-community-color">
  <div class="container">
    <div class="title-community d-flex" style="justify-content: space-between">
      <h3>Bienvenue sur la commauté FoodClass.</h3>
      <p>
        <a class="button-small" data-bs-toggle="collapse" href="#collapseForm" role="button" aria-expanded="false" aria-controls="collapseExample">
          Partager un post !
        </a>
      </p>
    </div>
  </div>

  <div class="container">
    <div class="container-form">
      <%= simple_form_for @post do |f| %>
        <div class="collapse" id="collapseForm">
          <span>
            <%= f.input :content, class: "form-white", label: false, placeholder: "Partager un post ici" %>
          </span>
          <div class="d-flex" style="align-items: flex-start;">
            <div class="card-new-form">
              <%= f.association :course, label: false, collection: @courses, prompt: "Quel cours ?" %>
            </div>
            <div class="card-new-form" >
              <%= f.input :photo, label: false, as: :file %>
            </div>
            <div>
              <%= f.submit "Publier", class: "button-small"%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="">
      <% @posts.each do |post| %>
        <div id="post-<%= post.id %>" >
          <div class="card-community">
            <div class="d-flex" style="align-items: flex-start;">
              <div>
                <%= image_tag post.participation.user.photo, class: "avatar-large mx-3" %>
              </div>
              <div class="card-community-title">
                <p><%= post.participation.user.nickname %> a commenté la recette <span class="card-community-title"> <%= link_to post.course.title, course_path(post.course) %></span> par
                  <%= post.course.chef.user.first_name %>
                  <%= post.course.chef.user.last_name %>
                </p>
                <p><strong> posté <%= l(post.posted_at, format: "%A %d %B %Y à %Hh%M") %></strong></p>
              </div>
            </div>
            <div class="card-community-description">
              <p>
                <%= post.content %>
              </p>
              <br>
            </div>
            <div class="card-photo">
              <% if post.photo.attached? %>
                <%= cl_image_tag(post.photo.key) %>
              <% end %>
            </div>
            <div class="">
              <div class="card-comments">
                <div class="emojis-dropdown d-flex mt-2" style="justify-content: space-between">
                  <%= render 'shared/emojis', post: post %>
                  <div>
                    <p>
                      <a class="text-comments" data-bs-toggle="collapse" href="#collapseComments" role="button" aria-expanded="false" aria-controls="collapseExample">
                        <%= pluralize(post.comments.count,"commentaire", "commentaires") %>
                      </a>
                    </p>
                  </div>
                </div>
                </div>
              </div>
              <div class="collapse" id="collapseComments">
                <% post.comments.each do |comment| %>
                  <div class="card-community-comments" id="comment-<%= comment.id %>">
                    <div class="d-flex">
                      <%= image_tag comment.user.photo, class: "avatar-mini" %>
                      <div class="post-comment-content">
                        <p><%= comment.content %></p>
                      </div>
                      <div class="button-delete-comment">
                        <% if current_user.comments.include? comment %>
                          <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Es-tu sûr?" } do %>
                            <%= image_tag("cancel.png") %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <div class="container-form-comments">
                  <%= simple_form_for [post, comment = Comment.new], remote: true do |f| %>
                    <%= f.input :content, label: false %>
                    <div class="button-comment-dropdown">
                        <%= f.submit "Commenter", label: false, class: "button-small" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="d-flex card-community-margin" style="align-items: flex-start;">
              <div class="button-delete button-delete-post">
                <% if post.participation.user == current_user %>
                  <%= link_to post_path(post), method: :delete do %>
                    <%= image_tag("cancel.png") %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="card-community-margin">
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>